# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# Make prompt a single line instead of two lines
# [line_break]
# disabled = true


format = '\[ [$username](red)@$hostname $directory$git_branch$git_status\] \$ $cmd_duration'

# Username
[username]
show_always = true
format = "$user"

# Hostname
[hostname]
ssh_only = false
format = "$hostname"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
truncation_length = 1

[c]
disabled = true



